### ISSUE TITLE
Cargo install failing

### ISSUE THREAD

**Issue by shepherd1530** [google/evcxr#198]
I can't seem to install evcxr_jupyter with cargo. I tried

```
brew install zeromq pkg-config
cargo install evcxr_jupyter --no-default-features
```

But I get a long stack trace output.

```
error[E0599]: no method named `sweep` found for struct `QueryTable<'_, TraitImplsInCrateQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, TraitImplsInCrateQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, TraitImplsInCrateQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, TraitImplsInCrateQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, TraitImplsInDepsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, TraitImplsInDepsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, TraitImplsInDepsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, TraitImplsInDepsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, AssociatedTyDataQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, AssociatedTyDataQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, AssociatedTyDataQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, AssociatedTyDataQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, TraitDatumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, TraitDatumQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, TraitDatumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, TraitDatumQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, StructDatumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, StructDatumQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, StructDatumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, StructDatumQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, ImplDatumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, ImplDatumQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, ImplDatumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, ImplDatumQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, FnDefDatumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, FnDefDatumQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, FnDefDatumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, FnDefDatumQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, ReturnTypeImplTraitsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, ReturnTypeImplTraitsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, ReturnTypeImplTraitsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, ReturnTypeImplTraitsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternCallableDefQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternCallableDefQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternCallableDefQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternCallableDefQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternTypeParamIdQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternTypeParamIdQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternTypeParamIdQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternTypeParamIdQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternImplTraitIdQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternImplTraitIdQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternImplTraitIdQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternImplTraitIdQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternClosureQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternClosureQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternClosureQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternClosureQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, AssociatedTyValueQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, AssociatedTyValueQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, AssociatedTyValueQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, AssociatedTyValueQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, TraitSolveQueryQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, TraitSolveQueryQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, TraitSolveQueryQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, TraitSolveQueryQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, FileSymbolsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, FileSymbolsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, FileSymbolsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, FileSymbolsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, LibrarySymbolsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, LibrarySymbolsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, LibrarySymbolsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, LibrarySymbolsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, LocalRootsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, LocalRootsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, LocalRootsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, LocalRootsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, LibraryRootsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, LibraryRootsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, LibraryRootsQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, LibraryRootsQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, LineIndexQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, LineIndexQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, LineIndexQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, LineIndexQuery>`
...
132 | /         sweep_each_query![
133 | |             // SourceDatabase
134 | |             base_db::ParseQuery
135 | |             base_db::CrateGraphQuery
...   |
213 | |             crate::LineIndexQuery
214 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternMacroQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternMacroQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternMacroQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternMacroQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternFunctionQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternFunctionQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternFunctionQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternFunctionQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternStructQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternStructQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternStructQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternStructQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternUnionQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternUnionQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternUnionQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternUnionQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternEnumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternEnumQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternEnumQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternEnumQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternConstQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternConstQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternConstQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternConstQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternStaticQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternStaticQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternStaticQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternStaticQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternTraitQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternTraitQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternTraitQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternTraitQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternTypeAliasQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternTypeAliasQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternTypeAliasQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternTypeAliasQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternImplQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternImplQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternImplQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternImplQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternTypeParamIdQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:111:32
    |
111 |                   $q.in_db(self).sweep(sweep);
    |                                  ^^^^^ method not found in `QueryTable<'_, InternTypeParamIdQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sweep` found for struct `QueryTable<'_, InternTypeParamIdQuery>` in the current scope
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_ide_db-0.0.66/src/apply_change.rs:118:32
    |
118 |                   $q.in_db(self).sweep(sweep.discard_everything());
    |                                  ^^^^^ method not found in `QueryTable<'_, InternTypeParamIdQuery>`
...
222 | /         sweep_each_query![
223 | |             // AstDatabase
224 | |             hir::db::InternMacroQuery
225 | |
...   |
238 | |             hir::db::InternTypeParamIdQuery
239 | |         ];
    | |__________- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 164 previous errors

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `ra_ap_ide_db`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `evcxr_jupyter v0.11.0`, intermediate artifacts can be found at `/var/folders/07/w9mfx9yn3z710mwsrlrtgdmm0000gp/T/cargo-installp49cJY`

Caused by:
  build failed
```

**Comment by dmilith** [comment]
Yeah, same here. Completely unable to build the project.

**Comment by davidlattimore** [comment]
Thanks for the report. A crate that we indirectly depend on made a breaking change without doing a proper version bump.

I've released 0.12.0 to fix it.

**Comment by shepherd1530** [comment]
@davidlattimore Thanks, but installing still fails. A new error is thrown on the console

```
   Compiling ra_ap_hir_ty v0.0.76
error[E0658]: use of unstable library feature 'control_flow_enum': new API
 --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:5:17
  |
5 | use std::{iter, ops::ControlFlow, sync::Arc};
  |                 ^^^^^^^^^^^^^^^^
  |
  = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:440:24
    |
440 |                 return ControlFlow::Break(());
    |                        ^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:442:13
    |
442 |             ControlFlow::Continue(())
    |             ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:457:62
    |
457 |     callback: &mut dyn FnMut(&Canonical<Ty>, AssocItemId) -> ControlFlow<()>,
    |                                                              ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:458:6
    |
458 | ) -> ControlFlow<()> {
    |      ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:497:13
    |
497 |             ControlFlow::Continue(())
    |             ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:523:66
    |
523 |     mut callback: &mut dyn FnMut(&Canonical<Ty>, AssocItemId) -> ControlFlow<()>,
    |                                                                  ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:524:6
    |
524 | ) -> ControlFlow<()> {
    |      ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:583:66
    |
583 |     mut callback: &mut dyn FnMut(&Canonical<Ty>, AssocItemId) -> ControlFlow<()>,
    |                                                                  ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:584:6
    |
584 | ) -> ControlFlow<()> {
    |      ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:614:5
    |
614 |     ControlFlow::Continue(())
    |     ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:625:66
    |
625 |     mut callback: &mut dyn FnMut(&Canonical<Ty>, AssocItemId) -> ControlFlow<()>,
    |                                                                  ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:626:6
    |
626 | ) -> ControlFlow<()> {
    |      ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:648:62
    |
648 |     callback: &mut dyn FnMut(&Canonical<Ty>, AssocItemId) -> ControlFlow<()>,
    |                                                              ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:649:6
    |
649 | ) -> ControlFlow<()> {
    |      ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:703:5
    |
703 |     ControlFlow::Continue(())
    |     ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:741:62
    |
741 |     callback: &mut dyn FnMut(&Canonical<Ty>, AssocItemId) -> ControlFlow<()>,
    |                                                              ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:742:6
    |
742 | ) -> ControlFlow<()> {
    |      ^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:745:24
    |
745 |         None => return ControlFlow::Continue(()),
    |                        ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error[E0658]: use of unstable library feature 'control_flow_enum': new API
   --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ra_ap_hir_ty-0.0.76/src/method_resolution.rs:781:5
    |
781 |     ControlFlow::Continue(())
    |     ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #75744 <https://github.com/rust-lang/rust/issues/75744> for more information

error: aborting due to 20 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ra_ap_hir_ty`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `evcxr_jupyter v0.12.0`, intermediate artifacts can be found at `/tmp/cargo-installzC3O3q`

Caused by:
  build failed
```

**Comment by shepherd1530** [comment]
@davidlattimore That works. Thanks.
